apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  replicas: 1
  serviceName: keycloak-service
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: docker.io/ontotext/poolparty-keycloak:2.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: https
              containerPort: 8443
            - name: http
              containerPort: 8080
            - name: health
              containerPort: 9000
          args:
            - "start"
            - "--import-realm"
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-admin
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-admin
                  key: password
            - name: POOLPARTY_SUPER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pp-secret
                  key: password
            - name: POOLPARTY_KEYCLOAK_LOGIN_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: pp-secret
                  key: clientSecret
            - name: KC_HOSTNAME
              value: keycloak.127.0.0.1.nip.io
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HTTP_PORT
              value: "8080"
            - name: KC_HTTPS_PORT
              value: "8443"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /mnt/certificates/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /mnt/certificates/tls.key
            - name: KC_PROXY_HEADERS
              value: xforwarded
            - name: KC_HEALTH_ENABLED
              value: "true"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
              scheme: HTTPS
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
              scheme: HTTPS
            failureThreshold: 600
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 1700Mi
            limits:
              memory: 2Gi
          volumeMounts:
            - name: keycloak-tls-certificates
              mountPath: /mnt/certificates
      volumes:
        - name: keycloak-tls-certificates
          secret:
            secretName: keycloak-tls
