{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-operator.fullname" . }}
  namespace: {{ include "keycloak-operator.namespace" . }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
      {{- with .Values.service.labels }}
      {{- tpl (toYaml .) $ | nindent 4 }}
      {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.service.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "keycloak-operator.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.healthCheckNodePort }}
  healthCheckNodePort: {{ .Values.service.healthCheckNodePort }}
  {{- end }}
  {{- if .Values.service.loadBalancerClass }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{ .Values.service.externalIPs | toYaml | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.deployment.containerPorts.http }}
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- with .Values.service.extraPorts -}}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
