{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-operator.serviceAccountName" . }}
  namespace: {{ include "keycloak-operator.namespace" . }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.serviceAccount.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
