{{- if and .Values.rdf4j.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rdf4j.serviceAccountName" . }}
  namespace: {{ include "unified-views.namespace" . }}
  labels:
    {{- include "rdf4j.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.annotations) .Values.serviceAccount.annotations) }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
