configuration:
  properties:
    # It isn't necessary to define this property as it is generated, if missing.
    MIRROR_CONFIG: /app/server-map.json

  existingServerMap:
    # The name of the Secret object.
    secret: mirror-app-server-secret
    # Key in the Secret object that holds the JSON content.
    secretKey: Server-map.json
    # The path where the server map JSON file will be mounted.
    mountPath: /app/Server-map.json
