#
# Official Helm chart for UnifiedViews.
#
apiVersion: v2
name: unified-views
description: |
  The Graphwise UnifiedViews (UV) is an ETL tool designed to extract, transform, and load data across various data
  sources including graph databases. It connects seamlessly with one or more Graphwise Platform instances, enabling
  efficient data integration and management.
type: application
version: 0.2.0 # TODO
appVersion: 10.2.3 # TODO
kubeVersion: ^1.34.0-0
home: https://help.graphwise.ai/en/graph-automation/graphwise-unifiedviews.html
icon: https://graphwise.ai/wp-content/uploads/2024/10/graphwise-logo-horizontal-slogan.svg
maintainers:
  - name: Graphwise
    email: dnd@graphwise.ai
sources:
  - https://github.com/poolparty-semantic-suite/charts
keywords:
  - graphwise
  - graph modeling
  - unified-views
  - etl
  - rdf
  - graphdb
  - semantic
  - poolparty
