#
# Official Helm chart for GraphViews.
#
apiVersion: v2
name: graphviews
description: |
  With GraphViews you can discover the many hidden connections, develop a view of the big picture and view
  your data with the help of graph visualizations.
type: application
version: 0.1.1 # TODO
appVersion: 1.0.0 # TODO
kubeVersion: ^1.34.0-0
home: https://help.graphwise.ai/en/graphwise-platform-overview/graphwise-sub-components-at-a-glance/graphwise-graphviews.html
maintainers:
  - name: Graphwise
    email: dnd@graphwise.ai
sources:
  - https://github.com/poolparty-semantic-suite/charts
keywords:
  - graphwise
  - graph modeling
  - visualization
  - poolparty
  - graphviews
