configuration:
  # The URL at which the Semantic Workbench application is accessible.
  externalUrl: http://semantic-workbench.127.0.0.1.nip.io/SemanticWorkbench

  properties:
    # The URL of PoolParty. Note that this address should not contain the /PoolParty context path.
    POOLPARTY_URL: http://poolparty.127.0.0.1.nip.io

    # The public URL of the Keycloak.
    KEYCLOAK_PUBLIC_URL: http://keycloak.127.0.0.1.nip.io/auth

    # The internal URL of the Keycloak in the cluster.
    # Format: http://<service-name>.<namespace>:<port>/<context-path>
    KEYCLOAK_INTERNAL_URL: http://keycloak-service.keycloak:8080/auth

    # This is the client secret for the Keycloak client registration used by PoolParty for authentication.
    # Consider using secret passed through "extraEnvFrom".
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PPT_CLIENTSECRET: yaOd67b2HdQ28hmvuWvZMpn3TLrmhZ1u
