apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adf.fullname.configmap.environment" . }}
  namespace: {{ include "adf.namespace" . }}
  labels:
    {{- include "adf.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  PP_JAVA_OPTS: >-
    {{ tpl .Values.configuration.defaultJavaArguments . }}
    {{ tpl .Values.configuration.javaArguments . }}
