#
# Official Helm chart for Graph Modeling.
#
apiVersion: v2
name: poolparty # TODO
description: |
  Graph Modeling is a taxonomy and ontology management tool that streamlines how enterprises organize and connect
  data—ensuring AI agents have a clean, governed, and reliable foundation to drive real ROI.
type: application
version: 0.3.3 # TODO
appVersion: 10.2.2 # TODO
kubeVersion: ^1.34.0-0
home: https://graphwise.ai/components/graph-modeling
icon: https://graphwise.ai/wp-content/uploads/2024/10/graphwise-logo-horizontal-slogan.svg
maintainers:
  - name: Graphwise
    email: dnd@graphwise.ai
sources:
  - https://github.com/poolparty-semantic-suite/charts
keywords:
  - graphwise
  - graph modeling
  - graphdb
  - semantic
  - poolparty
