---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  replicas: 1
  serviceName: keycloak-service
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
        - name: keycloak
          image: ontotext/poolparty-keycloak:2.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: https
              containerPort: 8443
            - name: http
              containerPort: 8080
            - name: health
              containerPort: 9000
          args:
            - "start"
            - "--import-realm"
          env:
            - name: KEYCLOAK_ADMIN
              value: "poolparty_auth_admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: POOLPARTY_SUPER_ADMIN_PASSWORD
              value: "poolparty"
            - name: POOLPARTY_KEYCLOAK_LOGIN_CLIENTSECRET
              value: "Kugwr5dv4wSkpBdtlnDFbLuXdl05yApZ"
            - name: KC_HOSTNAME
              value: "[KEYCLOAK_FQDN]"
            - name: KC_HTTP_RELATIVE_PATH
              value: /auth
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: xforwarded
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
    - name: health
      port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
spec:
  rules:
    - host: "[KEYCLOAK_FQDN]"
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
