apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unified-views.fullname.configmap.environment" . }}
  namespace: {{ include "unified-views.namespace" . }}
  labels:
    {{- include "unified-views.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  PP_JAVA_OPTS: >-
    {{ tpl .Values.configuration.defaultJavaArguments . }}
    {{ tpl .Values.configuration.javaArguments . }}
