#
# Official Helm chart for ADF.
#
apiVersion: v2
name: adf
description: |
  The Graphwise Application Development Framework (ADF) is a low-code development framework for the Graphwise Platform.
  The framework allows you to easily create and train semantic AI applications.
type: application
version: 0.1.3 # TODO
appVersion: 1.8.2 # TODO
kubeVersion: ^1.34.0-0
home: https://help.graphwise.ai/pp10.0/en/graphrag/semantic-search/graphwise-adf.html
icon: https://graphwise.ai/wp-content/uploads/2024/10/graphwise-logo-horizontal-slogan.svg
maintainers:
  - name: Graphwise
    email: dnd@graphwise.ai
sources:
  - https://github.com/poolparty-semantic-suite/charts
keywords:
  - graphwise
  - graphdb
  - semantic
  - adf
  - graph modeling
  - poolparty
