#
# Official Helm chart for the Graphwise Platform
#
apiVersion: v2
name: graphwise-platform
description: The Graphwise Platform
type: application
version: 0.1.0-alpha
appVersion: 1.0.0-alpha
kubeVersion: ^1.26.0-0

dependencies:

  # GraphDB
  - name: graphdb
    version: 12.1.1
    repository: https://maven.ontotext.com/repository/helm-public/
    condition: graphdb.enabled

  # Elasticsearch Operator
  - name: eck-operator
    version: 3.1.0
    repository: https://helm.elastic.co
    condition: eck-operator.enabled
